#!/bin/bash

#SBATCH --job-name=template
#SBATCH --ntasks-per-node=4
#SBATCH --mem=16G
#SBATCH --time=01:00:00

echo "[INFO] Pulling Python v3.8 container..."
singularity pull docker://python:3.8-bookworm

echo "[INFO] Installing qsm-forward"
singularity exec python_3.8-bookworm.sif pip install --user qsm-forward==0.23

echo "[INFO] Starting main.py..."
singularity exec python_3.8-bookworm.sif python3 main.py

